version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"

  server:
    build: ./server
    container_name: server-container
    ports:
      - "5050:5050"
    depends_on:
      - mongodb

  client:
    build: ./client
    container_name: client-container
    ports:
      - "3000:3000"
    depends_on:
      - server